#!/usr/bin/env python3
"""Build RANDO_BACKUP_AUDIT_2026-06-23.xlsx — audit of all gemp backups for
fixes / versions / runtime files Rando might be missing. Generated by K-2."""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

OUT = "/Users/steve/gemp-swccg-public/RANDO_BACKUP_AUDIT_2026-06-23.xlsx"

HDR_FILL = PatternFill("solid", fgColor="1F3864")
HDR_FONT = Font(bold=True, color="FFFFFF", size=11)
TITLE_FONT = Font(bold=True, size=14, color="1F3864")
WRAP = Alignment(wrap_text=True, vertical="top")
TOP = Alignment(vertical="top")
GREEN = PatternFill("solid", fgColor="C6EFCE")   # present / no action
YELLOW = PatternFill("solid", fgColor="FFEB9C")  # action (deploy/build)
GREY = PatternFill("solid", fgColor="E7E6E6")    # info / clutter
THIN = Border(*[Side(style="thin", color="BFBFBF")] * 4)

wb = openpyxl.Workbook()

def style_header(ws, row, ncols):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.fill = HDR_FILL; cell.font = HDR_FONT; cell.alignment = WRAP; cell.border = THIN

def put_rows(ws, rows, start, fills=None):
    for i, r in enumerate(rows):
        for j, v in enumerate(r):
            cell = ws.cell(row=start + i, column=j + 1, value=v)
            cell.alignment = WRAP; cell.border = THIN
        if fills and fills[i]:
            for j in range(len(r)):
                ws.cell(row=start + i, column=j + 1).fill = fills[i]

# ---------- Sheet 1: Summary ----------
s = wb.active; s.title = "Summary"
s["A1"] = "Rando Cal — Backup Audit (fixes / versions / runtime files)"; s["A1"].font = TITLE_FONT
s["A2"] = "Date: 2026-06-23   Author: K-2 (session c5d15b23)   Target install: /Users/steve/gemp-swccg-public"
s["A2"].font = Font(italic=True, color="595959")
summary = [
    ["BOTTOM LINE", "Nothing needs to be merged from any backup for Rando's decision logic. The current install already holds the union of every branch's fixes (V3-V185) and is the most complete version that exists on disk."],
    ["Do we have all the FIXES?", "YES. Every V-tag referenced by every backup branch (V29-V91, the full V67 family, experimental V44-V45, up to V184) was verified present in the current code. Orphan git commits exist but are a history artifact (the V184 branch was a squashed import), not missing logic."],
    ["Do we have all the VERSIONS?", "YES. Current install = V185 (highest anywhere). Source branch ai-improvements-v91 = V184; everything else tops out at V91 or is a 0-V-tag devs stub."],
    ["Are we missing EXTRA FILES Rando reads?", "NO. Rando reads ZERO external data files at decision time (0 matches for getResource/new File/Files.read/FileReader across the entire AI source tree). All knowledge is compiled into .java classes; there are no data/config files to merge."],
    ["The ONLY real gaps (NOT a merge)", "(1) V185 weapon-deployability fix is built in source this session but not yet in the running jar - needs a rebuild. (2) Three rules were discussed but never coded in ANY version (Mapuzo trap-counter, far-behind save-a-Jedi skip, Jedi Levitation/Sith Fury turn-4 retrieve gate) - see RANDO_MISSING_LOGIC.md. These are BUILD tasks, not merges."],
    ["Council status", "Local LLM council bridge is UP, but only deepseek-r1:70b-llama-distill-q8_0 is pulled while the role config wants deepseek-r1:70b / qwen3:32b / qwen3-coder:30b / llama3.3:70b -> live /deliberate 404s. Audit conclusion does not depend on it."],
]
r = 4
for k, v in summary:
    s.cell(row=r, column=1, value=k).font = Font(bold=True); s.cell(row=r, column=1).alignment = TOP
    s.cell(row=r, column=2, value=v).alignment = WRAP
    r += 1
s.column_dimensions["A"].width = 34; s.column_dimensions["B"].width = 110
for row in range(4, r):
    s.row_dimensions[row].height = 60

# ---------- Sheet 2: Merge Candidates ----------
m = wb.create_sheet("Merge Candidates")
m["A1"] = "Merge Candidates — what (if anything) to bring over from backups"; m["A1"].font = TITLE_FONT
cols = ["#", "Item / fix / file", "Type", "Found in (backup / branch)", "In current install?", "Merge needed?", "Recommendation / notes"]
for j, c in enumerate(cols): m.cell(row=3, column=j + 1, value=c)
style_header(m, 3, len(cols))
rows = [
    [1, "All AI fixes V21-V184 (every V-tag)", "Code", "ai-improvements-v91 (+ branches: backup-stable, exciting-beaver, peaceful-kepler, rando-improvements, v44-v45, v66-memory-audit, v91, srd-rando-tree-import)", "YES - verified V29-V185 all present", "NO", "Current install is the union of every branch's logic. Orphan commits are squashed-import history, not lost code."],
    [2, "Experimental V44-V45 (AMSD force check, off-objective penalties, Piett ground block, immune forfeit)", "Code", "v44-v45-experimental", "YES (V44, V45 present)", "NO", "Already merged into current."],
    [3, "V67 family (V67b/f/g/h/i/j/k/l/m/n)", "Code", "backup-stable-20260502", "YES (all present)", "NO", "Already merged into current."],
    [4, "Hunt Down / V35 family (Vader+Inquisitors+Hatred, IAYF, battle aggression)", "Code", "claude/peaceful-kepler", "YES (V35 widely present)", "NO", "Already merged into current."],
    [5, "DeckOracle off-by-one fix (bound matched[] loops to matched.length)", "Code", "backup-stable, v66-memory-audit, v91", "YES (applied at DeckOracle:266 & 1467)", "NO", "Re-applied in current; current is MORE correct than the raw ai-improvements-v91 source, which still has the buggy allCards.size()."],
    [6, "V185 weapon-deployability gate (reserve-pull needs a legal holder)", "Code", "None - built this session", "Source only (compiles); NOT in running jar", "DEPLOY", "Rebuild the jar to make V185 live. See AI_CHANGELOG 2026-06-23."],
    [7, "Runtime data files Rando reads for decisions", "Data", "None exist in any copy", "N/A", "NO", "Rando reads 0 external files (verified: 0 getResource/File/Files.read across full AI tree). Knowledge is all in .java. Nothing to merge."],
    [8, "Mapuzo trap-counter (clear OPPONENT off Safehouse/Corridor)", "Logic - never built", "Not in ANY backup", "NO", "BUILD", "Discussed, never coded. Only Rando's own-Jedi transit exists (V53b/V67z). See RANDO_MISSING_LOGIC.md / feedback_hidden_path_counter_and_levitation."],
    [9, "Far-behind skip of 'lose 1 Force to save a Jedi'", "Logic - never built", "Not in ANY backup", "NO", "BUILD", "Discussed, never coded. V53b always saves (+500), no far-behind exception."],
    [10, "Jedi Levitation / Sith Fury turn-4 retrieve gate", "Logic - never built", "Not in ANY backup", "NO", "BUILD", "Discussed, never coded. Only empty-pile + Sith-Fury-turn-1 guards exist, not a turn-4 timing gate."],
    [11, "Stray snapshots: CardSelectionEvaluator.java.bak / .v13.backup / .v24.11.fix", "Old code (clutter)", "Current install (AI tree)", "Present (not compiled/loaded)", "NO", "V13/V22/V24 era (2.4k-3.4k lines), superseded by live 9,238-line V185. Safe to delete; keep if you want the history."],
]
fills = [GREEN, GREEN, GREEN, GREEN, GREEN, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, GREY]
put_rows(m, rows, 4, fills)
widths = [4, 38, 16, 40, 26, 14, 60]
for j, w in enumerate(widths): m.column_dimensions[chr(65 + j)].width = w
for row in range(4, 4 + len(rows)): m.row_dimensions[row].height = 58
m.freeze_panes = "A4"

# ---------- Sheet 3: Backup Inventory ----------
b = wb.create_sheet("Backup Inventory")
b["A1"] = "Backup Inventory — every gemp copy on disk"; b["A1"].font = TITLE_FONT
cols = ["Copy / path", "mtime", "Highest Rando V-tag", "rando lines", "git branch (checked out)", "Role / verdict"]
for j, c in enumerate(cols): b.cell(row=3, column=j + 1, value=c)
style_header(b, 3, len(cols))
inv = [
    ["gemp-swccg-public  (CURRENT / LIVE)", "Jun 23", "V185", "39,931", "master (Rando files untracked)", "Live install - MOST COMPLETE version on disk"],
    ["gemp-swccg-public-BACKUP-2026-06-20", "Jun 22", "V184", "39,786", "ai-improvements-v91", "SOURCE of current Rando (current = this + off-by-one fix + V185)"],
    ["gemp-swccg-public-OURS-2026-06-20", "Jun 20", "V184 (on 'ai-improvements' branch)", "13,993 (working tree = stub)", "run-devs-pure (stub)", "Sibling repo; ai-improvements branch = same V184 logic"],
    ["gemp-swccg-public-PUBLIC-COPY-2026-06-22", "Jun 22", "V91", "18,026", "master @6011a406", "Broken public release (does not compile); reference only"],
    ["gemp-swccg-public-PUREDEVS-DB-2026-06-22", "Jun 20", "none (0 V-tags)", "13,993", "master @55c22cf49", "Devs stub + his 159-deck DB (DB is the value, not the AI)"],
    ["gemp-swccg-public-backup-20260524-175932", "May 24", "none", "-", "not-git", "Old stub copy - nothing unique"],
    ["gemp-swccg-public-backup-20260524-181047", "May 24", "none", "-", "not-git", "Old stub copy - nothing unique"],
    ["Downloads/gemp-swccg-master", "May 24", "none", "13,993", "not-git", "Devs stub - nothing unique"],
    ["Downloads/gemp-swccg-master 2", "Jun 22", "none", "13,993", "not-git", "Devs stub - nothing unique"],
    ["gemp-swccg-dojo", "May 9", "none", "13,993", "not-git", "Old devs stub - nothing unique"],
    ["gemp_db_backups / gemp_snapshots", "May", "n/a", "-", "-", "DB backups/snapshots only - no AI code"],
]
put_rows(b, inv, 4)
b.cell(row=4, column=1).fill = GREEN
b.cell(row=5, column=1).fill = YELLOW
widths = [42, 10, 24, 16, 30, 52]
for j, w in enumerate(widths): b.column_dimensions[chr(65 + j)].width = w
for row in range(4, 4 + len(inv)): b.row_dimensions[row].height = 42
b.freeze_panes = "A4"

# ---------- Sheet 4: Method & Evidence ----------
e = wb.create_sheet("Method & Evidence")
e["A1"] = "How the audit was done (reproducible)"; e["A1"].font = TITLE_FONT
cols = ["Step", "What I ran / checked", "Result"]
for j, c in enumerate(cols): e.cell(row=3, column=j + 1, value=c)
style_header(e, 3, len(cols))
method = [
    ["1. Version census", "For every gemp copy: count rando .java lines, distinct V-tags, highest V-num, key evaluator sizes; record git branch + last commit.", "Current install = V185 / 39,931 lines / 155 distinct V-tags - most complete. All other copies <= V91 or 0-tag stubs."],
    ["2. Confirm origin", "diff -q current CardSelectionEvaluator.java vs BACKUP-2026-06-20/ai-improvements-v91.", "BYTE-IDENTICAL. Current Rando came from that branch (V184) + off-by-one fix + V185."],
    ["3. Orphan-commit hunt", "git log <baseline>..<branch> -- <rando path> for all ~25 branches in BACKUP + OURS.", "Several branches show commits 'not in' baseline - but they are squashed-import history."],
    ["4. V-tag presence (decisive)", "grep -rw each orphan-branch V-tag (V29..V91, V67b-n, V44/45, etc.) in current code.", "ALL PRESENT. Zero MISSING. Confirms orphan commits are history, not lost logic."],
    ["5. Runtime-file scan", "grep -rniE 'getResourceAsStream|getResource|new File|Files.read|FileReader|FileInputStream|Paths.get|ClassLoader' across the full AI tree.", "0 matches. Rando reads NO external files at runtime -> no data files to merge."],
    ["6. Stragglers", "Checked May-24 backups, Downloads copies, dojo (all 0-tag stubs), stray .bak snapshots (V13-24, superseded), DB/snapshot dirs (no AI).", "Nothing unique anywhere."],
    ["Caveat (honesty)", "'All V-tags present' is verified by grep + presence counts; behavioral correctness of each is not re-tested here. The 3 never-built rules are absent by grep + no V-tag (strong, grep-based).", "Conclusion is high-confidence; re-run steps 4-5 any time to re-verify."],
]
put_rows(e, method, 4)
widths = [22, 70, 60]
for j, w in enumerate(widths): e.column_dimensions[chr(65 + j)].width = w
for row in range(4, 4 + len(method)): e.row_dimensions[row].height = 56
e.freeze_panes = "A4"

wb.save(OUT)
print("WROTE", OUT)
print("sheets:", wb.sheetnames)
