grep -riH ajax-loader.gif *
grep -riH ccgLeagueLogo.jpg *
grep -riH collapsed.jpg *
grep -riH coolsaber.wav *
grep -riH darkForce-42.png *
grep -riH darkHand-42.png *
grep -riH darkHand.png *
grep -riH darkOutOfPlay-42.png *
grep -riH darkPodracer-42.png *
grep -riH darkSabaccHand-42.png *
grep -riH deprecatedCard.png *
grep -riH gold.png *
grep -riH gray.jpg *
grep -riH incompleteCard.png *
grep -riH lightForce-42.png *
grep -riH lightHand-42.png *
grep -riH lightHand.png *
grep -riH lightOutOfPlay-42.png *
grep -riH lightPodracer-42.png *
grep -riH lightSabaccHand-42.png *
grep -riH pause.png *
grep -riH pixel.png *
grep -riH play.png *
grep -riH silver.png *
grep -riH vista-dn.gif *
grep -riH vista-dn-hover.gif *
grep -riH vista-up.gif *
grep -riH vista-up-hover.gif *
