---

name: Build GEMP Server

on:
  push:
    branches:
      - master

jobs:
  build-gemp:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 1
          path: gemp-swccg-private

      - name: Install Java via OpenJDK
        run:  |
          which java ; true
          java -version ; true
          sudo apt-get update
          sudo update-java-alternatives --set /usr/lib/jvm/temurin-21-jdk-amd64
          sudo apt-get --only-upgrade install maven
          java -version ; true

      - name: Maven Build
        run: |
          export STARTDIR=$(pwd)
          echo
          echo "Starting Directory: [$(pwd)]"
          echo
          cd gemp-swccg-private/src
          mvn clean install

      - name: list jars
        run: |
          ls gemp-swccg-private/src/gemp-swccg-async/target/web.jar ; true
          md5sum gemp-swccg-private/src/gemp-swccg-async/target/web.jar ; true

      - name: Replicate changes to public repo
        run: |
          cd "${STARTDIR}"
          echo "${{ secrets.GEMP_SWCCG_PUBLIC_SSH }}" > gemp-swccg-public.pem
          chmod 0600 gemp-swccg-public.pem
          echo
          echo "Setting GIT_SSH_COMMAND"
          export GIT_SSH_COMMAND="ssh -i gemp-swccg-public.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          echo "git clone gemp-swccg-public"
          git clone git@github.com:PlayersCommittee/gemp-swccg-public.git gemp-swccg-public
          echo "rsync changes to public"
          # set501 is the playtesting cards and they must be excluded.
          # .git and .github are specific to their repositories.
          rsync --exclude=set501 --exclude=.git --exclude=.github -av gemp-swccg-private/ gemp-swccg-public/
          cd gemp-swccg-public/
          git config --local user.email "devon+github-actions[bot]@hubner.org"
          git config --local user.name "github-actions[bot]"
          git status
          git add -A .
          git commit -m "Merging changes from upstream" -a ; true
          export GIT_SSH_COMMAND="ssh -i ../gemp-swccg-public.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          echo "Pushing changes to gemp-swccg-public"
          GIT_SSH_COMMAND="ssh -i ../gemp-swccg-public.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git push ; true
          rm ../gemp-swccg-public.pem



