---

# This action may no longer be needed, or may need retooled
# to fit the modern docker paradigm. 
# It's now intended that performing production releases looks
# like this:
# 1- Open the container within Portainer
# 2- git pull
# 3- mvn install
# 4- Restart the container in Portainer 
# These steps may be performable using Github actions, but 
# it's unknown at this time if they could be performed
# remotely in the right place.
# At any rate, there's no longer a need to prepare an artifact
# for transfer, as it now never leaves the docker container.
name: Create GEMP Server Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-gemp:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master

      - name: Install Java via OpenJDK
        run:  |
          which java ; true
          java -version ; true
          sudo apt-get install -y openjdk-21-jdk-headless
          export JAVA_HOME=/usr/lib/jvm/temurin-21-jdk-amd64
          sudo apt-get --only-upgrade install maven
          java -version ; true
          

      - name: Maven Build
        working-directory: ./src
        run: mvn clean install

      # https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ""
          draft: true
          prerelease: false

      # https://github.com/actions/upload-release-asset
      - name: Upload web.jar to Release
        id: upload_release_asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./src/gemp-swccg-async/target/web.jar
          asset_name: web.jar
          asset_content_type: application/zip



