---

name: Promote to Public GEMP Repository

on:
  push:
    branches:
      - master

jobs:
  build-gemp:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 1
          path: gemp-swccg-private
          
      - name: Replicate changes to public repo
        run: |
          cd "${STARTDIR}"
          echo "${{ secrets.GEMP_SWCCG_PUBLIC_SSH }}" > gemp-swccg-public.pem
          chmod 0600 gemp-swccg-public.pem
          echo
          echo "Setting GIT_SSH_COMMAND"
          export GIT_SSH_COMMAND="ssh -i gemp-swccg-public.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          echo "git clone gemp-swccg-public"
          git clone git@github.com:PlayersCommittee/gemp-swccg-public.git gemp-swccg-public
          echo "rsync changes to public"
          # set501 is the playtesting cards and they must be excluded.
          # .git and .github are specific to their repositories.
          rsync --exclude=set501 --exclude=.git --exclude=.github -av --delete gemp-swccg-private/ gemp-swccg-public/
          cd gemp-swccg-public/
          git config --local user.email "rules@starwarsccg.org"
          git config --local user.name "github-actions[bot]"
          git status
          git add -A .
          git commit -m "Merging changes from upstream" -a ; true
          export GIT_SSH_COMMAND="ssh -i ../gemp-swccg-public.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          echo "Pushing changes to gemp-swccg-public"
          GIT_SSH_COMMAND="ssh -i ../gemp-swccg-public.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git push ; true
          rm ../gemp-swccg-public.pem



