name: test-on-push
on:
  push:
    branches:
      - master
      - main

  pull_request:
    types:
    - opened
    - edited
    - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build the stack
        working-directory: ./src/docker
        run: |
          docker compose build
          docker compose up -d
          
      - name: Building Gemp within the container using Maven
        run: |
          docker exec gemp_swccg_app_1 mvn clean install
          
      - name: Restarting container post-rebuild
        working-directory: ./src/docker
        run: |
          docker compose restart

      - name: Client Test
        run: |
          curl -s --retry 10 --retry-connrefused http://127.0.0.1:17001/gemp-swccg/index.html
          echo "Python3: $(which python3)"
          echo "pip3...: $(which pip3)"
          pip3 install -r src/requirements.txt
          python3 src/gemp_client_test.py

