name: test-on-push
on:
  push:
    branches:
      - master
      - main

  pull_request:
    types:
    - opened
    - edited
    - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Java via OpenJDK
        run:  |
          which java ; true
          java -version ; true
          sudo apt-get update
          sudo apt-get install -y openjdk-21-jdk-headless
          update-java-alternatives --list
          java -version ; true

      - name: Maven build
        working-directory: ./src
        run: mvn clean install

        #I'm pretty sure that this is redundant; 
        # mvn install already runs mvn test
      - name: Maven re-test
        working-directory: ./src
        run: mvn test

      - name: Build the stack
        working-directory: ./src/docker
        run: |
          docker-compose build
          docker-compose up -d

      - name: Client Test
        run: |
          docker exec gemp curl -s --retry 10 --retry-connrefused http://127.0.0.1:8080/gemp-swccg/index.html
          echo "Python3: $(which python3)"
          echo "pip3...: $(which pip3)"
          pip3 install -r src/requirements.txt
          python3 src/gemp_client_test.py

